version: '3'

services:

  # http:
  #   image: app-http
  #   build:
  #     context: .
  #     dockerfile: ./services/testing/http/Dockerfile
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./build/client:/wwwroot
  #   environment:
  #     - NODE_ENV=TESTING
  #   depends_on:
  #     - application

  cache:
    image: app-redis
    build:
      context: .
      dockerfile: ./services/testing/cache/Dockerfile
    ports:
      - "6379:6379"
    environment:
      - NODE_ENV=TESTING

  # db:
  #   image: app-db
  #   build:
  #     context: .
  #     dockerfile: ./services/testing/db/Dockerfile
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - NODE_ENV=TESTING

  application:
    image: application
    build:
      context: .
      dockerfile: ./Dockerfile.test
      args:
        - NODE_ENV=TESTING
    ports:
      - "9000:9000"
    depends_on:
      - db
      - cache
    command: /opt/app/tests.sh
    environment:
      - NODE_ENV=TESTING
