workflows:
  version: 2
  build-and-test:
    jobs:
     build:
       docker:
         - image: sebastianconcept/hello-world:latest
       steps:
         - checkout
         - run: echo "hello world"

    test:
      docker:
        - image: circleci/node:4.8.2
        - image: mongo:3.4.4
      steps:
        - checkout
        - run:
            name: Test
            command: ./run-test.sh
      - test:
          requires:
            - build
          filters:
            branches:
              only: master